"""ProblemDetail domain model following RFC 7807 problem+json specification."""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


class ProblemDetail(BaseModel):
    """RFC 7807 problem detail payload.

    Parameters
    ----------
    type : str
        A URI reference or stable slug identifying the error problem type.
    title : str
        A short, human-readable summary of the problem type.
    status : int
        The HTTP status code generated by the origin server.
    detail : str or None, optional
        A human-readable explanation specific to this occurrence of the problem.
    instance : str or None, optional
        A URI reference that identifies the specific occurrence of the problem.
    extra : dict[str, Any], optional
        Additional contextual metadata regarding the failure.
    """

    type: str
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None
    extra: dict[str, Any] = Field(default_factory=dict)


class StudioDomainError(Exception):
    """Base class for domain and adapter errors in GLP Studio."""

    status_code: int = 500


class Neo4jUnavailableError(StudioDomainError):
    """Raised when Neo4j is not configured or cannot establish a connection."""

    status_code: int = 503


class Neo4jReadOnlyViolationError(StudioDomainError):
    """Raised when a write query is attempted in read-only Cypher mode."""

    status_code: int = 403


class QueryTimeoutError(StudioDomainError):
    """Raised when a graph or Cypher query exceeds its time budget."""

    status_code: int = 504


class ResultTooLargeError(StudioDomainError):
    """Raised when query results exceed the row or node budget cap."""

    status_code: int = 413


class OverlayNotImplementedError(StudioDomainError):
    """Raised when an overlay kind is reserved or not yet implemented."""

    status_code: int = 501


class InvalidConfigPatchError(StudioDomainError):
    """Raised when a configuration patch contains invalid keys or fails validation."""

    status_code: int = 422

